Fatemeh Amanian

•Create three random tensors, including a 3 * 3 tensor as float, a 4 * 4 tensor as double, and a 5 * 3 * 4 tensor as short type:

In [1]:
import torch

print("Imported!")

Imported!


•Change their elements in the GPU:

In [2]:
a = torch.rand(3, 3, dtype=torch.float)
b = torch.rand(4, 4, dtype=torch.double)
c = torch.randint(10, (5, 3, 4), dtype=torch.short)


print(" a: \n", a)
print("\n b: \n", b)
print("\n c: \n", c)

 a: 
 tensor([[0.2846, 0.2663, 0.0358],
        [0.3134, 0.6986, 0.7027],
        [0.1764, 0.0387, 0.8290]])

 b: 
 tensor([[0.5932, 0.8423, 0.6633, 0.6152],
        [0.6251, 0.2348, 0.0880, 0.2586],
        [0.7575, 0.6982, 0.2299, 0.3420],
        [0.6454, 0.5159, 0.8085, 0.3504]], dtype=torch.float64)

 c: 
 tensor([[[0, 0, 2, 1],
         [3, 3, 4, 3],
         [3, 6, 4, 4]],

        [[8, 0, 5, 6],
         [1, 8, 6, 0],
         [3, 8, 5, 3]],

        [[4, 6, 2, 1],
         [0, 6, 0, 6],
         [2, 6, 9, 9]],

        [[0, 9, 4, 6],
         [2, 4, 0, 4],
         [0, 0, 0, 5]],

        [[6, 3, 6, 7],
         [4, 6, 9, 4],
         [8, 6, 3, 4]]], dtype=torch.int16)


In [3]:
# First create gpu tensor:
device = torch.device("cuda")

# torch.cuda.FloatTensor(1000, 1000).fill_(0)
# with torch.cuda.device(1):
#     a_gpu = torch.randn(3, 3, dtype=torch.float).cuda(device)
#     b_gpu = torch.randn(4, 4, dtype=torch.double).cuda(device)
#     c_gpu = torch.randn(10, (5, 3, 4), dtype=torch.short).cuda(device)
a_gpu = torch.cuda.FloatTensor(3, 3).random_()
b_gpu = torch.cuda.DoubleTensor(4, 4).random_()
c_gpu = torch.cuda.ShortTensor(5, 3, 4).random_()

print(" a_gpu:", a_gpu)
print("\n b_gpu:", b_gpu)
print("\n c_gpu:", c_gpu)
# Then we change the cells:
a_gpu[1,2] = 0.0
b_gpu[1,:] = torch.tensor([0, 0, 0, 0])
c_gpu[0,:,:] =  torch.tensor(
    [
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ]
)

print("\n a_gpu:", a_gpu)
print("\n b_gpu:", b_gpu)
print("\n c_gpu:", c_gpu)

 a_gpu: tensor([[ 1289892.,   232549.,    80542.],
        [13043976.,   287579., 13220967.],
        [15400037.,  8167349., 11062332.]], device='cuda:0')

 b_gpu: tensor([[3.1191e+15, 4.3581e+15, 4.8495e+15, 5.1102e+15],
        [3.0040e+15, 3.8618e+15, 6.1918e+14, 6.6076e+15],
        [1.8738e+15, 5.5065e+15, 4.8425e+15, 6.8001e+14],
        [4.7670e+15, 4.5914e+15, 5.6427e+15, 5.0657e+15]], device='cuda:0',
       dtype=torch.float64)

 c_gpu: tensor([[[ 6364, 19959, 15365,   151],
         [16504,  2572,  4011,  7065],
         [21224, 10916,  9239, 30882]],

        [[19493, 12948, 26103, 14130],
         [  549, 27773, 23080, 10071],
         [19562, 30507, 26454, 10740]],

        [[21378,  8487, 21772, 20214],
         [17496, 14153, 29462, 13989],
         [ 2145, 19889,  3658, 10241]],

        [[  880,  7130, 11780,  7254],
         [29357, 27814,  6015,  4651],
         [21811, 32655, 32332,  9647]],

        [[ 2572, 10919, 17792, 31354],
         [19424, 19080, 14491, 181

 •Display the order of its elements and its transpose in the memory then use storage offset and contiguous:

In [4]:
# Display the order of its elements:
d = torch.randint(10, (4, 4), dtype=torch.short)
d[0,:] = torch.tensor([-1, -1, -1, -1])

print(" d: \n" , d)
d_t = d.transpose(0,1)
print("\n d transposed: \n", d_t)

print(" d in memory: \n" , d.storage())
d_t = d.transpose(0,1)
print("\n d transposed in the memory: \n", d_t.storage())

# See wether it's contiguous or not:
print("\n Is d contiguous?: ", d.is_contiguous())
print("\n Is d transposed contiguous?: ", d_t.is_contiguous())

# Make it contiguous:
d_t_contig = d_t.contiguous()

print("\n Make d_t contiguous: \n")
print("\n d_t_contig: \n", d_t_contig)
print("\n d_t_contig in memory: \n", d_t_contig.storage())


# Cut the tensor:
d_cut = d[1,:]
print("\n d cutted: \n", d_cut)
print("\n d cutted in memory: \n", d_cut.storage())
print("\n d cutted offset: \n", d_cut.storage_offset())

 d: 
 tensor([[-1, -1, -1, -1],
        [ 1,  1,  2,  9],
        [ 9,  2,  6,  3],
        [ 5,  2,  4,  1]], dtype=torch.int16)

 d transposed: 
 tensor([[-1,  1,  9,  5],
        [-1,  1,  2,  2],
        [-1,  2,  6,  4],
        [-1,  9,  3,  1]], dtype=torch.int16)
 d in memory: 
  -1
 -1
 -1
 -1
 1
 1
 2
 9
 9
 2
 6
 3
 5
 2
 4
 1
[torch.ShortStorage of size 16]

 d transposed in the memory: 
  -1
 -1
 -1
 -1
 1
 1
 2
 9
 9
 2
 6
 3
 5
 2
 4
 1
[torch.ShortStorage of size 16]

 Is d contiguous?:  True

 Is d transposed contiguous?:  False

 Make d_t contiguous: 


 d_t_contig: 
 tensor([[-1,  1,  9,  5],
        [-1,  1,  2,  2],
        [-1,  2,  6,  4],
        [-1,  9,  3,  1]], dtype=torch.int16)

 d_t_contig in memory: 
  -1
 1
 9
 5
 -1
 1
 2
 2
 -1
 2
 6
 4
 -1
 9
 3
 1
[torch.ShortStorage of size 16]

 d cutted: 
 tensor([1, 1, 2, 9], dtype=torch.int16)

 d cutted in memory: 
  -1
 -1
 -1
 -1
 1
 1
 2
 9
 9
 2
 6
 3
 5
 2
 4
 1
[torch.ShortStorage of size 16]

 d cutted 

•Save and load one among the elements of tensors using the torch and the h5py file:

In [5]:
import h5py
 
# Saving:
f = h5py.File('file.h5', 'w')
f.create_dataset('data', data=c)
f.close()
# Loading:
f = h5py.File('file.h5','r')
c_new = f['data'][:]
f.close()
 
print("\n tensor c after loading: \n", c_new)


 tensor c after loading: 
 [[[0 0 2 1]
  [3 3 4 3]
  [3 6 4 4]]

 [[8 0 5 6]
  [1 8 6 0]
  [3 8 5 3]]

 [[4 6 2 1]
  [0 6 0 6]
  [2 6 9 9]]

 [[0 9 4 6]
  [2 4 0 4]
  [0 0 0 5]]

 [[6 3 6 7]
  [4 6 9 4]
  [8 6 3 4]]]


•Show the different true and false requires_grad values in Autograd by the backward method:

In [6]:

# Autograd: autograd is a tool to take differentiation and
#  calculating gradients of tensors inside the neural model.

# Create a simple graph model:
# x = torch.rand(2, 2, dtype=torch.float)
x = torch.tensor(
    [
        [1.0, 2.0],
        [3.0, 4.0]
    ]
)
print("\n x: \n", x)

# Track the tensor x so its gradient could be calculated later:
x.requires_grad = True

# y = torch.rand(2, 2, dtype=torch.float)
y = torch.tensor(
    [
        [5.0, 6.0],
        [7.0, 8.0]
    ]
)
print("\n y: \n", y)

# Define a function:
z = x * y + x
print("\n z = x * y + x: \n", z)

# Do a backpropagation:
# (gives an error if no tensor has set its requires_grad attribute to False)
z = z.sum()
z.backward()

print("\n gradient of dz/dx (should be y + 1): \n", x.grad)


 x: 
 tensor([[1., 2.],
        [3., 4.]])

 y: 
 tensor([[5., 6.],
        [7., 8.]])

 z = x * y + x: 
 tensor([[ 6., 14.],
        [24., 36.]], grad_fn=<AddBackward0>)

 gradient of dz/dx (should be y + 1): 
 tensor([[6., 7.],
        [8., 9.]])
